version: "3.9"

services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    container_name: qbittorrent
    environment:
      #- PAGID=10000
      - PGID=1000
      - PUID=1000
      - QBT_EULA=${QBT_EULA}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      - TZ=Asia/Shanghai
      #- UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:${QBT_VERSION}
    ports:
      # for bittorrent traffic
      - 6881:6881/tcp
       - 6881:6881/udp
      # for WebUI
      - ${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}/tcp
    volumes:
      - ${QBT_CONFIG_PATH}:/config/qBittorrent
      - <downloasds目录>:/downloads
      # 如果使用自定义目录, 需使用绝对路径, 不能挂载外部volume
      - /mnt/video/movie/:/movie
      - /mnt/video/anime/:/anime
      - /mnt/video/series/:/series